# Generated by Django 6.0.7 on 2026-07-26 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_problem', models.TextField()),
                ('technical_fidings', models.TextField(blank=True)),
                ('solution_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('AWAITING_PARTS', 'Aguardando peças'), ('IN_PROGRESS', 'Em andamento'), ('AWAITING_APPROVAL', 'Aguardando aprovação'), ('COMPLETED', 'Concluído'), ('DELIVERED', 'Entregue'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Urgente')], default=2)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='clients.client')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='equipments.equipment')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'opened_at'],
                'indexes': [models.Index(fields=['status'], name='service_ord_status_a5c9d7_idx'), models.Index(fields=['technician', 'status'], name='service_ord_technic_087553_idx')],
            },
        ),
    ]
