# Generated by Django 6.0.7 on 2026-07-26 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service_orders", "0002_serviceorderitem_servicetimeline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceorder",
            options={
                "ordering": ["-priority", "opened_at"],
                "verbose_name_plural": "Ordens de Serviço",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceorderitem",
            options={"verbose_name_plural": "Itens do serviço"},
        ),
    ]
