# Generated by Django 6.0.7 on 2026-07-29 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_address_alter_client_created_at_and_more'),
        ('equipments', '0003_alter_equipment_accessories_alter_equipment_brand_and_more'),
        ('service_orders', '0003_alter_serviceorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completada em'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregue em'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='equipments.equipment', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço estimado'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço final'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Aberta em'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Aberta por'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Urgente')], default=2, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='reported_problem',
            field=models.TextField(verbose_name='Problema relatado'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='solution_description',
            field=models.TextField(blank=True, verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iniciada em'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='technical_fidings',
            field=models.TextField(blank=True, verbose_name='Problema técnico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Técnico'),
        ),
        migrations.AlterField(
            model_name='serviceorderitem',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='serviceorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='serviceorderitem',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service_orders.serviceorder', verbose_name='Ordem de serviço'),
        ),
        migrations.AlterField(
            model_name='serviceorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='servicetimeline',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='servicetimeline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='servicetimeline',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servicetimeline',
            name='service_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='service_orders.serviceorder', verbose_name='Ordem de serviço'),
        ),
        migrations.AlterField(
            model_name='servicetimeline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
