# Generated by Django 6.0.7 on 2026-09-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0004_alter_serviceorder_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorderitem',
            options={'ordering': ['id'], 'verbose_name_plural': 'Itens do serviço'},
        ),
    ]
