# Generated by Django 6.0.7 on 2026-09-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0005_rename_technical_fidings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='technical_fidings',
            new_name='technical_findings',
        ),
    ]
