# Generated by Django 6.0.7 on 2026-07-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="notification_prefs",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Preferências"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("tech", "Técnico"),
                    ("attendant", "Atendente"),
                ],
                default="tech",
                max_length=20,
                verbose_name="Função",
            ),
        ),
    ]
