# Generated by Django 6.0.7 on 2026-07-26 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipment",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Equipamentos",
            },
        ),
    ]
