# Generated by Django 6.0.7 on 2026-07-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_client_address_alter_client_created_at_and_more"),
        (
            "equipments",
            "0003_alter_equipment_accessories_alter_equipment_brand_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Número de série"
            ),
        ),
        migrations.AddConstraint(
            model_name="equipment",
            constraint=models.UniqueConstraint(
                fields=("client", "serial_number"),
                name="unique_serial_number_per_client",
            ),
        ),
    ]
